Honor manually_* fields when filtering companies by company segments.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -142,7 +142,7 @@ jobs:
   # need to separate different code utilities to different processes, because if running in one "thread"
   # there is an issue with the order/env variables/other means
   # which does not allow the build to complete.
-  misc:
+  mautic:
     runs-on: ubuntu-latest
 
     # these should contain latest stable PHP and Mautic versions
@@ -227,6 +227,73 @@ jobs:
             bin/console lint:twig ${{ env.PLUGIN_DIR }}
           elif [[ "${{ matrix.commands }}" == "CS Fixer" ]]; then
             bin/php-cs-fixer fix ${{ env.PLUGIN_DIR }} --config=.php-cs-fixer.php -v --dry-run --using-cache=no --show-progress=dots --diff
+          else
+            echo "Invalid command"
+            exit 1
+          fi
+  bundle:
+    runs-on: ubuntu-latest
+
+    # these should contain latest stable PHP and Mautic versions
+    strategy:
+      fail-fast: false
+      matrix:
+        commands: [ 'PHPStan', 'CS Fixer', 'Rector' ]
+        php-versions: [ '8.3' ]
+        mautic-versions: [ '5.x' ]
+
+    name: ${{ matrix.commands }} - ${{ matrix.php-versions }} - ${{ matrix.mautic-versions }}
+
+    steps:
+      - name: Checkout Bundle
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Rector Cache
+        if: ${{matrix.commands == 'Rector'}}
+        uses: actions/cache@v4
+        with:
+          path: ./var/cache/rector
+          key: ${{ runner.os }}-rector-bundle-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
+          restore-keys: |
+            ${{ runner.os }}-rector-bundle-${{ hashFiles('**/composer.lock') }}
+            ${{ runner.os }}-rector-bundle-
+
+      - name: PHPStan Cache
+        if: ${{matrix.commands == 'PHPStan'}}
+        uses: actions/cache@v4
+        with:
+          path: ./var/phpstan-cache
+          key: ${{ runner.os }}-phpstan-bundle-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
+          restore-keys: |
+            ${{ runner.os }}-phpstan-bundle-${{ hashFiles('**/composer.lock') }}
+            ${{ runner.os }}-phpstan-bundle-
+
+      - name: Setup PHP, with composer and extensions
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: ${{ matrix.php-versions }}
+          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
+          ini-values: opcache.enable_cli=0
+
+      - name: Install dependencies
+        uses: "ramsey/composer-install@v3"
+
+      - name: Run ${{ matrix.commands }}
+        run: |
+          if [[ "${{ matrix.commands }}" == "PHPStan" ]]; then
+#            composer remove --dev rector/rector
+#            php ${{ env.PLUGIN_DIR }}/.github/phpstan-config.php
+#            cat phpstan.neon
+            export SYMFONY_ENV=dev
+            export APP_ENV=dev
+            export APP_DEBUG=1
+            ./vendor/bin/phpstan
+          elif [[ "${{ matrix.commands }}" == "Rector" ]]; then
+            ./vendor/bin/rector process --dry-run --ansi
+          elif [[ "${{ matrix.commands }}" == "CS Fixer" ]]; then
+            ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php -v --dry-run --show-progress=dots --diff
           else
             echo "Invalid command"
             exit 1
